spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt-test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
  jpa:
    show-sql: true
  mvc:
    path-match:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml

logging:
  level:
    org:
      springframework:
        security: info
springfox:
  documentation:
    swagger-ui:
      enabled: true
