taco:
  orders:
    pageSize: 5
spring:
  datasource:
    url: jdbc:mysql://localhost/db
    username: root
    password: 'secret-pw'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update